In [1]:
import numpy as np
tensor_0D = np.array(5)
print("Average grade: \n{}".format(tensor_0D))
print("Tensor dimensions: \n{}".format(tensor_0D.ndim))

Average grade: 
5
Tensor dimensions: 
0


In [2]:
tensor_1D = np.array([4,6,8])
print("Subject grades: \n{}".format(tensor_1D))
print("Tensor dimensions: \n{}".format(tensor_0D.ndim))

Subject grades: 
[4 6 8]
Tensor dimensions: 
0


In [3]:
# 2D Tensor (matrix)
tensor_2D = np.array([[0, 1, 1],  # Subject 1
                      [2, 3, 3],  # Subject 2
                      [1, 3, 2]])  # Subject 3
print("Exam grades are:\n{}".format(tensor_2D))
print("Subject 1:\n{}".format(tensor_2D[0]))
print("Subject 2:\n{}".format(tensor_2D[1]))
print("Subject 3:\n{}".format(tensor_2D[2]))
print("Tensor dimensions: \n{}".format(tensor_2D.ndim))

Exam grades are:
[[0 1 1]
 [2 3 3]
 [1 3 2]]
Subject 1:
[0 1 1]
Subject 2:
[2 3 3]
Subject 3:
[1 3 2]
Tensor dimensions: 
2


In [4]:
tensor_3D = np.array([[[0, 1, 1],  # First quarter
                      [2, 3, 3],
                      [1, 3, 2]],
                     [[1, 3, 2],  # Second quarter
                      [2, 4, 2],
                      [0, 1, 1]]])
print("Exam grades per quarter are:\n{}".format(tensor_3D))
print("First quarter:\n{}".format(tensor_3D[0]))
print("Second quarter:\n{}".format(tensor_3D[1]))
print("Tensor dimensions: \n{}".format(tensor_3D.ndim))

Exam grades per quarter are:
[[[0 1 1]
  [2 3 3]
  [1 3 2]]

 [[1 3 2]
  [2 4 2]
  [0 1 1]]]
First quarter:
[[0 1 1]
 [2 3 3]
 [1 3 2]]
Second quarter:
[[1 3 2]
 [2 4 2]
 [0 1 1]]
Tensor dimensions: 
3


In [5]:
tensor_4D = np.array([[[[0, 1, 1], # Jacob
                      [2, 3, 3],
                      [1, 3, 2]],
                     [[1, 3, 2],
                      [2, 4, 2],
                      [0, 1, 1]]],
                      [[[0, 3, 1], # Christian
                      [2, 4, 1],
                      [1, 3, 2]],
                     [[1, 1, 1],
                      [2, 3, 4],
                      [1, 3, 2]]],
                     [[[2, 2, 4], # Sofia
                      [2, 1, 3],
                      [0, 4, 2]],
                     [[2, 4, 1],
                      [2, 3, 0],
                      [1, 3, 3]]]])
print("The grades of each student are:\n{}".format(tensor_4D))
print("Jacob's grades:\n{}".format(tensor_4D[0]))
print("Christian's grades:\n{}".format(tensor_4D[1]))
print("Sofia's grades:\n{}".format(tensor_4D[2]))
print("Tensor dimensions: \n{}".format(tensor_4D.ndim))

The grades of each student are:
[[[[0 1 1]
   [2 3 3]
   [1 3 2]]

  [[1 3 2]
   [2 4 2]
   [0 1 1]]]


 [[[0 3 1]
   [2 4 1]
   [1 3 2]]

  [[1 1 1]
   [2 3 4]
   [1 3 2]]]


 [[[2 2 4]
   [2 1 3]
   [0 4 2]]

  [[2 4 1]
   [2 3 0]
   [1 3 3]]]]
Jacob's grades:
[[[0 1 1]
  [2 3 3]
  [1 3 2]]

 [[1 3 2]
  [2 4 2]
  [0 1 1]]]
Christian's grades:
[[[0 3 1]
  [2 4 1]
  [1 3 2]]

 [[1 1 1]
  [2 3 4]
  [1 3 2]]]
Sofia's grades:
[[[2 2 4]
  [2 1 3]
  [0 4 2]]

 [[2 4 1]
  [2 3 0]
  [1 3 3]]]
Tensor dimensions: 
4
