In [1]:
import numpy as np

In [2]:
a = np.array([20,40,60,80])
a

array([20, 40, 60, 80])

In [3]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [4]:
c = a + b

In [5]:
c

array([20, 41, 62, 83])

In [6]:
a**2

array([ 400, 1600, 3600, 6400])

In [7]:
a>50

array([False, False,  True,  True])

In [8]:
a += 10

In [9]:
a

array([30, 50, 70, 90])

In [10]:
x = np.random.random(12)
x

array([0.35897912, 0.85634986, 0.21153763, 0.1499454 , 0.62300002,
       0.96932662, 0.15435606, 0.82723299, 0.94585271, 0.25446763,
       0.62513561, 0.38987822])

In [11]:
x.max()

0.9693266183602738

In [12]:
x.min()

0.14994540000577927

In [13]:
x.sum()

6.36606186938837

In [14]:
b = np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
b.sum(axis=0)

array([15, 18, 21, 24, 27])

In [16]:
b.sum(axis=1)

array([10, 35, 60])

In [17]:
b.max(axis=1)

array([ 4,  9, 14])

In [18]:
b.max(axis=0)

array([10, 11, 12, 13, 14])

In [19]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [20]:
b.cumsum(axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  7,  9, 11, 13],
       [15, 18, 21, 24, 27]])

In [21]:
k = np.random.random(10)
k

array([0.28615333, 0.72160312, 0.11851733, 0.13372939, 0.83426035,
       0.12635571, 0.40082537, 0.99109947, 0.10376627, 0.79102081])

In [22]:
k.mean()

0.45073311472479605

In [23]:
k.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [24]:
np.median(k)

0.343489352939964

In [25]:
np.std(k)

0.3308017343880712

In [26]:
np.var(k)

0.10942978747415599

In [27]:
copy = k.copy()
copy

array([0.28615333, 0.72160312, 0.11851733, 0.13372939, 0.83426035,
       0.12635571, 0.40082537, 0.99109947, 0.10376627, 0.79102081])

In [28]:
cities = np.array(["ank", "ist", "bursa", "ank", "izm", "bur", "izm"])

In [29]:
np.unique(cities)

array(['ank', 'bur', 'bursa', 'ist', 'izm'], dtype='<U5')